spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lsy1999/springboot01.git
          search-paths:
            - configfiles
      label: dev
server:
  port: 8888
